name: IceLegend
main: com.icelegend.IceLegend
version: 1.0
api-version: 1.13
commands:
   ice:
      description: Your description
      usage: /<command>
      permission: yourplugin.yourcommandpermission 