name: IceLegend
main: com.icelegend.IceLegend
version: 1.0
api-version: 1.13
commands:
   ice:
      description: open UI
      usage: /<command>
      permission: IceLegend.command.ice
   icelegend:
      description: get the command guide
      usage: /<command>
      permission: IceLegend.command.help
   skilltreegui:
      description: open skill tree interface
      usage: /<command>
      permission: IceLegend.command.skilltree
   attributegui:
      description: open attribute interface
      usage: /<command>
      permission: IceLegend.command.attributegui
   combineskillgui:
      description: open combine skill interface
      usage: /<command>
      permission: IceLegend.command.combineskillgui
   classgui:
      description: open class gui
      usage: /<command>
      permission: IceLegend.command.classgui
   selectclassgui:
      description: open select class interface
      usage: /<command>
      permission: IceLegend.command.selectclassgui
   itemcombinegui:
      description: open item combine gui
      usage: /<command>
      permission: IceLegend.command.item
   bindskillgui:
      description: open binding skill gui
      usage: /<command>
      permission: IceLegend.command.bindskillgui
   itemskincombinegui:
      description: open item combine interface
      usage: /<command>
      permission: IceLegend.command.itemcombinegui
   gemcombinegui:
      description: open gem combine interface
      usage: /<command>
      permission: IceLegend.command.gemcombinegui
   skillbar:
      description: open gem combine interface
      usage: /<command>
      permission: IceLegend.command.skillbar
   getitem:
      description: get specific item
      usage: /<command>
      permission: IceLegend.command.getitem
   getgem:
      description: get specific gem
      usage: /<command>
      permission: IceLegend.command.getgem
   getskin:
      description: get specific skin
      usage: /<command>
      permission: IceLegend.command.getskin
   getskillpoint:
      description: get skill point
      usage: /<command>
      permission: IceLegend.command.getskillpoint
   classopen:
      description: open locked class
      usage: /<command>
      permission: IceLegend.command.classopen
   giveitem:
      description: give specific item
      usage: /<command>
      permission: IceLegend.command.giveitem
   givegem:
      description: give specific gem
      usage: /<command>
      permission: IceLegend.command.givegem
   givemana:
      description: give specific mana
      usage: /<command>
      permission: IceLegend.command.givemana
   giveskin:
      description: give specific skin
      usage: /<command>
      permission: IceLegend.command.giveskin